server:
  port: 9999

spring:
#    mvc:
#        view:
#          prefix: /
#          suffix: .html
    datasource:
#        name: test
        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://132.232.39.186:3306/news?&useUnicode=true&characterEncoding=UTF8
#        username: root
#        password: root
        url: jdbc:mysql://127.0.0.1:3306/news?&useUnicode=true&characterEncoding=UTF8
        username: root
        password: admin
        type: com.alibaba.druid.pool.DruidDataSource
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    thymeleaf:
        prefix: classpath:/static/

    redis:
      host: 132.232.39.186
      port: 6379
    mail:
        host: smtp.qq.com
        username: 352512524@qq.com
        password: hxervlfnzxascafd



mybatis:
e: com.winter.model

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

